---
- name: Install Wazuh on multiple nodes
  hosts: wazuh-linux-agents
  become: yes
  tasks:
    - name: Download Wazuh Agent package
      get_url:
        url: 'https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.7.4-1_amd64.deb'
        dest: '/tmp/wazuh-agent_4.7.4-1_amd64.deb'

    - name: Install Wazuh Agent package
      shell: 'dpkg -i /tmp/wazuh-agent_4.7.4-1_amd64.deb'
      environment:
        WAZUH_MANAGER: '172.16.2.100'
        WAZUH_AGENT_GROUP: 'LinuxAgents'
        WAZUH_AGENT_NAME: '{{ inventory_hostname }}'

    - name: restart the linux host
      shell: 'systemctl daemon-reload && systemctl enable wazuh-agent && systemctl start wazuh-agent'
