name: Run Ansible Playbook

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Ansible playbook on remote VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/student
            git clone https://github.com/LucasCode812/Ansible-Individual-Project.git
            cd Ansible-Individual-Project
            ansible-playbook playbook.yml
        #    ansible-playbook -i inventory.yml playbook.yml
