name: Run Ansible Playbook

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Remove existing folder and clone repository
        run: |
          sudo rm -rf /home/student/Ansible-Individual-Project
          git clone https://github.com/LucasCode812/Ansible-Individual-Project.git /home/student/Ansible-Individual-Project

      - name: Install Wazuh on Environment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          command_timeout: 200m
          script: |
            cd /home/student/Ansible-Individual-Project
            ansible-playbook -i /etc/ansible/hosts WazuhInstall.yml -v

      - name: Install Wazuh Agents on Wazuh Cluster
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          command_timeout: 200m
          script: |
            cd /home/student/Ansible-Individual-Project
            ansible-playbook -i /etc/ansible/hosts WazuhClusterAgents.yml -v

      - name: Install Wazuh Agents on Windows Hosts
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          command_timeout: 200m
          script: |
            cd /home/student/Ansible-Individual-Project
            ansible-playbook -i /etc/ansible/hosts WindowsAgents.yml -v

      - name: Install Wazuh Agents on Linux Hosts
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          command_timeout: 200m
          script: |
            cd /home/student/Ansible-Individual-Project
            ansible-playbook -i /etc/ansible/hosts LinuxAgents.yml -v
